// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using issue_tracker_server.Data;

#nullable disable

namespace issue_tracker_server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913144532_AddBuildLookupTable")]
    partial class AddBuildLookupTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("issue_tracker_server.Models.Bug", b =>
                {
                    b.Property<int>("BugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BugId"));

                    b.Property<int>("AffectedBuildId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedBehavior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FixedBuildId")
                        .HasColumnType("int");

                    b.Property<int>("ImpactId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsibleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("BugId");

                    b.HasIndex("AffectedBuildId");

                    b.HasIndex("FixedBuildId");

                    b.HasIndex("ImpactId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ResponsibleId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VariantId");

                    b.ToTable("Bugs");
                });

            modelBuilder.Entity("issue_tracker_server.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Builds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "2.3.0"
                        },
                        new
                        {
                            Id = 2,
                            Name = "2.3.2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "2.3.4"
                        },
                        new
                        {
                            Id = 4,
                            Name = "2.3.5"
                        },
                        new
                        {
                            Id = 5,
                            Name = "2.3.6"
                        },
                        new
                        {
                            Id = 6,
                            Name = "2.3.7"
                        },
                        new
                        {
                            Id = 7,
                            Name = "2.3.8"
                        },
                        new
                        {
                            Id = 8,
                            Name = "2.3.9"
                        },
                        new
                        {
                            Id = 9,
                            Name = "2.4.0"
                        },
                        new
                        {
                            Id = 10,
                            Name = "2.4.1"
                        });
                });

            modelBuilder.Entity("issue_tracker_server.Models.Impact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Impacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cosmetic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Minor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Major"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Critical"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Blocker"
                        });
                });

            modelBuilder.Entity("issue_tracker_server.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Open"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Closed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Resolved"
                        },
                        new
                        {
                            Id = 4,
                            Name = "In Test"
                        },
                        new
                        {
                            Id = 5,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 6,
                            Name = "On Hold"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Needs Support"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Not an issue"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Change Request"
                        });
                });

            modelBuilder.Entity("issue_tracker_server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("issue_tracker_server.Models.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Variants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DE"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DELF7"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "UK"
                        });
                });

            modelBuilder.Entity("issue_tracker_server.Models.Bug", b =>
                {
                    b.HasOne("issue_tracker_server.Models.Build", "AffectedBuild")
                        .WithMany()
                        .HasForeignKey("AffectedBuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("issue_tracker_server.Models.Build", "FixedBuild")
                        .WithMany()
                        .HasForeignKey("FixedBuildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("issue_tracker_server.Models.Impact", "Impact")
                        .WithMany()
                        .HasForeignKey("ImpactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("issue_tracker_server.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("issue_tracker_server.Models.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("issue_tracker_server.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("issue_tracker_server.Models.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AffectedBuild");

                    b.Navigation("FixedBuild");

                    b.Navigation("Impact");

                    b.Navigation("Reporter");

                    b.Navigation("Responsible");

                    b.Navigation("Status");

                    b.Navigation("Variant");
                });
#pragma warning restore 612, 618
        }
    }
}
